language: node_js
node_js: "8"
sudo: required
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
  - yarn install
install:
  - npm install -g codecov
after_success:
  - chmod ugo+x ./scripts/pr_deploy.sh
  - bash ./scripts/pr_deploy.sh
  - chmod ugo+x ./scripts/pr_comments.sh
  - bash ./scripts/pr_comments.sh
script:
  - yarn test-ci
  - yarn build
cache:
  yarn: true
  directories:
    - node_modules
git:
  depth: 1

deploy:
  email: "mmarosi@redhat.com"
  provider: surge
  project: ./public/
  domain: data-driven-forms.surge.sh 
  skip_cleanup: true
